language: ruby
rvm:
  - 2.3.0
services:
  - docker
addons:
  apt:
    packages:
      - chromium-chromedriver
cache:
  bundler: true
  directories:
    - frontend/node_modules
    - "$HOME/.npm"

before_install:
  - nvm install 4.4.4
  - nvm use 4.4.4
  - npm install -g bower ember-cli

before_script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - cd frontend && npm install && cd ..
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bundle exec rake
  - bundle exec rake ember:test
  # Test e2e against docker image
  - RAILS_ENV=production PRECOMPILE=1 bin/rails assets:precompile
  - docker build -t "singularitiesorg/circular-work" .
  - docker-compose up -d
  # Wait for the db to start
  - sleep 10
  - DATABASE_URL=postgresql://postgres:dbpass@localhost:8054/postgres?pool=10 bundle exec rake db:schema:load
  - DATABASE_URL=postgresql://postgres:dbpass@localhost:8054/postgres?pool=10 bundle exec rake cucumber

after_success:
  - docker tag singularitiesorg/circular-work "singularitiesorg/circular-work:$TRAVIS_COMMIT"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push "singularitiesorg/circular-work:$TRAVIS_COMMIT"

notifications:
  webhooks:
    - secure: jBARkLflfrZLzYu/qYIK3o90JXyXJEM/lkYsTjch1A0B2u+wndbrF9QBmjjGTVk87RoYj7D4VK5lftayuzSt7Nf7D9I5ysKmjCU0ZixYc6SE1pHQTjpt9HqVyFE7zStdqdjb+3PZH/wDLOE83jpA7TjXu6Py0tPv5Qg2klty73UUlSRCmt/bpzx6vpL9ECVQ3e8j9WR1WXKSsQ4YCrYD5Ts0IOxa9uGwKq9C9O9V7+CyRTjuqMdwzyE1jowuJAxxEq0K9uL0oFg0xNN1DvouGQ6ehJ2ZoAqeWdgJMaQ+/SpynfxnM6C3AwhJNs6c+e4yqYp7Ka3CtFmvK/v+jmegTAyvFjoHQHqwo8ouvXHulEjFSPKGiseIKGGRZfzCsTR64FdJ7PPl3IBWKeRNbkKUB6JTAFJWhAXS6LNjvhYEVh4tpge0ZKQCOv215OvcV0vCTSAnFLWr9qxYx08FlC6Nzlea0NNArLs/SrHq8ySVsCLXcqn2snauJTrNZplbPQPzplXCjLnDCeoBlc/I5j6QGGeF6K0j3w/jHuHTvrhFt7hsgYQyYAYoJcLNvhUmGe6DEFKuUiCFoLHHwvf6qydqwrf5Qjl3ysfA58gruBdbGImY2+H12yBLbmyvZcoy3A4GmhElFGDgSeBk1jqRr3xDeoN0Y4H1wtNNbk/1NBKz2iQ=
