language: ruby
rvm:
  - 2.3.0
before_script:
  - "bundle exec rake db:migrate RAILS_ENV=test"
  - "nvm install 4.4.4"
  - "nvm local 4.4.4"
  - "cd frontend; npm install"
cache:
  - bundler
script:
  - bundle exec rake
