version: '2'
services:
  app:
    image: singularitiesorg/circular-work
    ports:
      - "127.0.0.1:8030:3000"
    environment:
      CI: 1
      DATABASE_URL: postgres://postgres:dbpass@db:5432?pool=10
      DEFAULT_HOST: example.com
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
      SECRET_KEY_BASE: c07bb904a05890a16cb532e299c83bd944bb58f6300c0e7f45902bf3fc19a51f954a5a93b0bcf639c307d0fcf5961d2b3e42634295d168aa547a346aa3145d0f
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dbpass
    ports:
      - "127.0.0.1:8054:5432"
